
/*
* Configuration of module: Can (Can_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    TC275
*
* Module vendor:           iSoft
* Generator version:       2.0.2
*
* Generated by iSoft Shanghai Software Lab 
*           on Tue Apr 29 17:33:33 CST 2018
*/

	
/*=======[I N C L U D E S]====================================================*/
#include "can.h"

/*=======[V E R S I O N   I N F O R M A T I O N]===============================*/
#define CAN_CFG_C_AR_MAJOR_VERSION     3 
#define CAN_CFG_C_AR_MINOR_VERSION     1 
#define CAN_CFG_C_AR_PATCH_VERSION     5 
#define CAN_CFG_C_SW_MAJOR_VERSION     1
#define CAN_CFG_C_SW_MINOR_VERSION     0
#define CAN_CFG_C_SW_PATCH_VERSION     0

/*=======[V E R S I O N  C H E C K]===========================================*/
#if (CAN_CFG_C_AR_MAJOR_VERSION != CAN_CFG_H_AR_MAJOR_VERSION)
#error "Can_Cfg.c:Mismatch in Specification Major Version"
#endif 
#if (CAN_CFG_C_AR_MINOR_VERSION != CAN_CFG_H_AR_MINOR_VERSION)
#error "Can_Cfg.c:Mismatch in Specification Minor Version"
#endif
#if (CAN_CFG_C_AR_PATCH_VERSION != CAN_CFG_H_AR_PATCH_VERSION)
#error "Can_Cfg.c:Mismatch in Specification Patch Version"
#endif
#if (CAN_CFG_C_SW_MAJOR_VERSION != CAN_CFG_H_SW_MAJOR_VERSION)
#error "Can_Cfg.c:Mismatch in Specification Major Version"
#endif
#if (CAN_CFG_C_SW_MINOR_VERSION != CAN_CFG_H_SW_MINOR_VERSION)
#error "Can_Cfg.c:Mismatch in Specification Minor Version"
#endif

/*=======[E X T E R N A L   D A T A]==========================================*/

/* HRHs first, HTH next */
/* Controller ID must be grouped together */
/* Can ID to ensure top priority IDs are first */
const Can_HardwareObjectType Can_HardwareObjectConfigData[CAN_MAX_HARDWAREOBJECTS] =
{
    {
        CAN_HANDLE_TYPE_BASIC,      /* CanHandleType */
        CAN_ID_TYPE_STANDARD,       /* CanIdType */
        0x7E4U,                     /* CanIdValue */
        (uint8)0,                   /* CanObjectId */
        CAN_OBJECT_TYPE_RECEIVE,    /* CanObjectType */
		CAN_CONTROLLER_0,           /* CanControllerRef */
        0x1FFFFFFFU                 /* CanFilterMask */
    },
    {
        CAN_HANDLE_TYPE_BASIC,      /* CanHandleType */
        CAN_ID_TYPE_STANDARD,       /* CanIdType */
        0x7DFU,                     /* CanIdValue */
        (uint8)1,                   /* CanObjectId */
        CAN_OBJECT_TYPE_RECEIVE,    /* CanObjectType */
		CAN_CONTROLLER_0,           /* CanControllerRef */
        0x1FFFFFFFU                 /* CanFilterMask */
    },
    {
        CAN_HANDLE_TYPE_BASIC,      /* CanHandleType */
        CAN_ID_TYPE_STANDARD,       /* CanIdType */
        0x214U,                     /* CanIdValue */
        (uint8)2,                   /* CanObjectId */
        CAN_OBJECT_TYPE_RECEIVE,    /* CanObjectType */
		CAN_CONTROLLER_0,           /* CanControllerRef */
        0x1FFFFFFFU                 /* CanFilterMask */
    },
    {
        CAN_HANDLE_TYPE_BASIC,      /* CanHandleType */
        CAN_ID_TYPE_STANDARD,       /* CanIdType */
        0x7ECU,                     /* CanIdValue */
        (uint8)3,                   /* CanObjectId */
        CAN_OBJECT_TYPE_TRANSMIT,   /* CanObjectType */
		CAN_CONTROLLER_0,           /* CanControllerRef */
        0xFFFFFFFFU                 /* CanFilterMask */
    }
};

const uint8 Can_HohConfigData[CAN_MAX_HOHS] =
{
        (uint8)0,
        (uint8)1,
        (uint8)2,
        (uint8)3
};
/* 500khz , BRP = 24, SJW = 2, Tseq1 = 4, Tseq2 = 1, fcan = 100M , SP = 75% */
const Can_ControllerConfigType Can_ControllerConfigData[CAN_MAX_CONTROLLERS] =
{
    {
    	0x1498U,     /* CanCtrlValue--> BaudRate:250 Kbps *//*250K~0x1C18U,500K~0x6193U 1M~0x5289U*/
        (uint8)0,    /* CanRxHwObjFirst */
        (uint8)3,    /* CanRxHwObjCount */
        (uint8)3,    /* CanTxHwObjFirst */
        (uint8)1     /* CanTxHwObjCount */
    }
};

const Can_ControllerPCConfigType Can_ControllerPCConfigData[CAN_MAX_CONTROLLERS] =
{
    {
        0xf0018200U,                /* CanControllerBaseAddr */
		CAN_CONTROLLER_0,           /* CanControllerId */
        (uint8)0,                   /* CanControllerId */
        TRUE,                       /* CanControllerActivation */
        CAN_PROCESS_TYPE_POLLING,   /* CanBusOffProcessing */
        CAN_PROCESS_TYPE_POLLING,   /* CanRxProcessing */
        CAN_PROCESS_TYPE_POLLING,   /* CanTxProcessing */
#if (STD_ON == CAN_WAKEUP_SUPPORT)
        CAN_PROCESS_TYPE_INTERRUPT, /* CanWakeupProcessing */
        (uint8)0,                   /* CanWakeupSourceRef */
#endif /* #if(STD_ON == CAN_WAKEUP_SUPPORT) */
        90000000UL                 /* CanCpuClock */
    }
};

/*=======[E N D   O F   F I L E]==============================================*/

